import {
  CommonButtonType,
  CommonMenuListProps,
  CommonGridCardSizeProps,
  CommonPositionProps,
  CommonLevelTypeProps,
  ExternalTypeProps,
  ThumbnailInfoProps,
  ThumbnailType,
  WorkListItemProps,
} from '@core/types';

export const PAGE_INFOS = {
  HOME: {
    name: 'Home',
    path: '/',
  },
  WORK: {
    name: 'Works',
    path: '/works',
  },
  ABOUT: {
    name: 'About',
    path: '/about',
  },
  RESUME: {
    name: 'Resume',
    path: '/resume',
  },
  DASHBOARD: {
    name: 'Dashboard',
    path: '/dashboard',
  },
};

// Header에 표시되는 메뉴 리스트.
export const CONSTANTS_MENU_LIST: CommonMenuListProps[] = [
  { name: PAGE_INFOS.HOME.name, path: PAGE_INFOS.HOME.path },
  { name: PAGE_INFOS.ABOUT.name, path: PAGE_INFOS.ABOUT.path },
  { name: PAGE_INFOS.RESUME.name, path: PAGE_INFOS.RESUME.path },
  { name: PAGE_INFOS.WORK.name, path: PAGE_INFOS.WORK.path },
  { name: PAGE_INFOS.DASHBOARD.name, path: PAGE_INFOS.DASHBOARD.path },
];

// Thumbnail Types
export const THUMBNAIL_TYPES: { [key in ThumbnailType]: ThumbnailType } = {
  ABOUT: 'ABOUT',
  RESUME: 'RESUME',
  WORK: 'WORK',
  OTHER: 'OTHER',
  HISTORY: 'HISTORY',
  PROJECT: 'PROJECT',
};

// Home 페이지에서 표시되는 카드 내부의 썸네일 컨텐츠
export const THUMBNAIL_LIST: ThumbnailInfoProps[] = [
  {
    type: THUMBNAIL_TYPES.ABOUT,
    main: `Hello, I'm I.Sak 👋`,
    sub: 'Front-End 개발을 즐거워하고 성장 욕구와 긍정적인 사고를 가진 개발자입니다.',
    target: '',
  },
  {
    type: THUMBNAIL_TYPES.RESUME,
    main: 'MY RESUME',
    sub: '이력서 상세보기',
    target: '',
  },
  {
    type: THUMBNAIL_TYPES.WORK,
    main: 'WEB SERVICE',
    sub: '핀다이렉트 Z',
    target: '',
  },
  {
    type: THUMBNAIL_TYPES.WORK,
    main: 'MOBILE APP',
    sub: 'NSD',
    target: '',
  },
  {
    type: THUMBNAIL_TYPES.WORK,
    main: 'IOT SERVICE',
    sub: '스마트 빌딩',
    target: '',
  },
  {
    type: THUMBNAIL_TYPES.HISTORY,
    main: 'WORK HISTORY',
    sub: '프로젝트 이력',
    target: '',
  },
  {
    type: THUMBNAIL_TYPES.HISTORY,
    main: 'DASHBOARD',
    sub: '프로젝트 통계',
    target: '',
  },
  {
    type: THUMBNAIL_TYPES.OTHER,
    main: `Let's work together 🙌`,
    sub: 'CONTACT ME',
    target: '',
  },
];

// WORK 페이지에서 표시되는 프로젝트 요약 카드 리스트
export const PROJECT_THUMNAIL_LIST: WorkListItemProps[] = [
  {
    workId: '28',
    imageName: 'img-security',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'ITSM Admin (통합관리자)',
    target: '',
    skill:
      'Next.js, Typescript, ITSM 컴포넌트, Turbo Repo, Recoil, React-Query, Emotion, Module Federation',
    introduction:
      'NSD, NCI 서비스와 이후에 추가될 ITSM 서비스를 하나의 관리자 서비스로 통합하여 관리 기능을 제공하는 서비스',
    taskList: [
      '프로젝트의 공용 및 전체적인 내용 관리',
      'Module Federation 도입 검토',
      'Local 환경 테스트 및 Dev Ops 팀과 협업으로 서버환경 구축하여 테스트',
      'host app, remote app을 Next Federation으로 셋업',
      '각각의 기존 서비스 관리자 기능을 하나의 container로 분리 및 remote app 셋업',
      'host app과 remote app 연결',
      '기획/디자인 리뷰 참여',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2024.07 ~ 2024.11',
    // reference: ,
  },
  {
    workId: '27',
    imageName: 'img-security',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'NCI Admin (장애관리 관리자)',
    target: '',
    skill:
      'Next.js, Typescript, ITSM 컴포넌트, Turbo Repo, Recoil, React-Query, Emotion, Web Socket, GA',
    introduction:
      '게임, 인증, 거래소 등 회사에서 등록한 모든 서비스에 대한 장애를 옵스지니를 통해 구독하여 장애 발생시 서비스 담당자 및 해당 서비스를 구독한 사용자에게 SMS, 이메일, 푸시알림 채널을 통하여 장애를 전파하고 현재 장애 상태를 실시간으로 표시하는 서비스',
    taskList: [
      '프로젝트 셋업',
      '프로젝트의 공용 및 전체적인 내용 관리',
      'Atomic Design 패턴 도입 (atom, molcules 단위까지)',
      '공용 Layout 컴포넌트 개발',
      '디자인 시스템으로 생성한 UI 컴포넌트로 프로젝트에 사용 될 공용 컴포넌트 개발(atom, molcules)',
      '로그인 페이지 개발',
      '관리자의 구독관리, 알림관리, 발송내역, 신고내역 페이지 개발',
      '디자이너와의 협업으로 Figma를 통하여 디자인 가이드 반영',
      '기획/디자인 리뷰 참여',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2024.03 ~ 2024.07',
    // reference: ,
  },
  {
    workId: '26',
    imageName: 'img-nsd-app',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Mobile'],
    workName: 'NSD App (서비스데스크 앱)',
    target: '',
    skill:
      'React Native, Expo, Typescript, Recoil, React-Query, Emotion, FCM, GA, Sentry, Azure AD, MS Intune',
    introduction:
      'NSD 웹서비스의 관리자 기능을 제외한 축소화 된 앱으로 사내망이 아닌 외부망에서도 타부서 및 타팀과의 업무 진행시 필요한 요청에 대해 상세 내용을 확인하고 승인, 결재, 반려 등의 기능을 앱으로 제공함으로써 시간과 장소에 제약을 받지 않고 업무를 지원하는 서비스',
    taskList: [
      'React Native 기술 검토 및 테스트',
      'Expo를 통한 프로젝트 셋업 및 공용 컴포넌트 개발',
      'WebView를 통하여 SSO와 웹에서 표시되는 요청 상세 내용을 동일하게 표시',
      'DeepLink를 통하여 버전에 따른 회사포털 앱 업데이트 유도',
      '결재, 처리, 요청, 상세페이지 개발',
      'FCM을 통한 push 알림 제공 및 알림 페이지 개발',
      '앱 내의 푸시알림 설정을 통한 디바이스 알림 설정 on/off 동기화',
      'Foreground, Background에 따른 상태관리',
      'MS Teams 연동',
      'AOS, IOS 빌드 및 Intune 관리센터에 앱 배포 관리',
      '보안플랫폼 팀과의 협업으로 intune wrapping, MS Azure 앱 등록 및 MAM 정책 적용',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드 내용 반영',
      '기획/디자인 리뷰 참여',
      '서비스 오픈 이후 운영과 고도화 내용 반영 진행중',
      'Trouble Shooting 및 이후 App 개발에 용이하도록 필요한 내용에 대해 문서화 (Intune Wrapping, IOS Certificate, Provisioning Profile, FCM, DeepLink 등)',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2023.04 ~ 2023.11',
    reference: '<div></div>',
  },
  {
    workId: '25',
    imageName: 'img-security',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'NSD (서비스데스크)',
    target: '',
    skill:
      'React.js, Typescript, ITSM 컴포넌트, Recoil, React-query, Emotion, React-flow, i18n, GA',
    introduction:
      '전사 협업 서비스로 국내/외 법인, 조직, 부서, 사용자 간의 협업을 위한 태스크 관리 및 업무 진행에 있어 필요로하는 모든 요청서 신청, 승인, 결재 등을 제공하고 관리자 페이지를 통해 조직 및 사용자, 권한, 워크플로우, 요청서, 공통코드 등 관리 기능을 제공하는 서비스',
    taskList: [
      '프로젝트 셋업',
      '디자인 시스템으로 생성한 UI 컴포넌트로 프로젝트에 사용 될 공용 컴포넌트 개발',
      'React-flow 라이브러리를 통해 워크플로우 개발',
      'Back-End 개발팀에 BFF API 도입 제안 및 도입',
      '워크플로우 조작 history를 쌓아 뒤로가기, 앞으로가기 초기화 기능 개발',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드 내용 반영',
      '기획/디자인 리뷰 참여',
      '서비스 오픈 이후 운영과 고도화 내용 반영 진행중',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2023.01 ~ 2023.11',
  },
  {
    workId: '24',
    imageName: 'img-security',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Design'],
    workName: '디자인 시스템',
    target: '',
    skill: 'React.js, Typescript, Storybook, Emotion, Rollup, Nexus',
    introduction:
      '공용 UI 컴포넌트 생성으로 기획, 디자인 직군과의 원활한 커뮤니케이션과 앞으로 진행 될 ITSM 서비스에 사용할 공용 UI 컴포넌트를 생성하여 제공',
    taskList: [
      '디자인 시스템에 있는 기능 명세와 디자인 가이드를 제플린을 통해 ITSM 서비스에서 사용 될 UI 컴포넌트 개발',
      '디자인 가이드에 명시된 typography, color, 공용으로 사용 될 Themes 셋업',
      'Rollup을 통해 사내 private 저장소인 Nexus에 업로드',
      '팀 내 Jira 태스크 관리 및 Naming 컨벤션, Git PR, Git Flow, 리뷰 도입',
      '디자인 검수 대응',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2022.07 ~ 2022.12',
    // reference: ,
  },
  {
    workId: '23',
    imageName: 'img-pindirectshop2.0',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: '핀다이렉트Z (자사몰)',
    target: '',
    skill:
      'Next.js, React.js, Typescript, React-query, Recoil, ES6, AWS S3, Emotion, Framer-motion',
    introduction:
      '현재 운영중인 핀다이렉트샵 1.0을 리뉴얼하고 보다 더 편리한 MVNO 주문 서비스 및 이벤트, 프로모션 제공',
    taskList: [
      '개편 된 서비스 및 리뉴얼 된 디자인에 필요한 공용 컴포넌트 개발',
      '유심 주문 서비스 개발',
      '주문 배송 관리 및 마이페이지 개발',
      '실시간 데이터 사용량, 부가서비스 가입/해지, 요금제 변경 개발',
      'KCP를 이용한 결제 연동',
      '1.0에서 판매 중이던 5G(MNO), 중고폰 서비스를 걷어내고 유심 위주의 MVNO 서비스 제공',
      '디자인 팀에서 요구하는 애니메이션을 Framer 및 CSS로 대응',
      'AWS S3에 이미지 리소스 교체',
      '디자인 팀과의 협업으로 Figma를 통해 디자인 가이드 내용 반영',
      '기획/디자인 리뷰 참여',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2022.01 ~ 2022.06',
    reference: 'https://www.pindirectshop.com/',
  },
  {
    workId: '22',
    imageName: 'img-pindirectshop-home',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: '핀다이렉트샵 (자사몰)',
    target: '',
    skill: 'React.js, React-redux, javascript, ES6, React-apexchart, AWS S3, Styled-components',
    introduction:
      '기존 스마트폰샵과 다르게 카카오톡 앱을 통해 휴대폰을 구매하는 것이 아닌 독립적인 채널 확보와 5G / 중고폰 / 중고폰 / 유심 등의 MNO, MVNO 주문과 주문부터 셀프개통까지의 서비스를 제공하고 자사망을 이용하는 고객을 관리하며 각 종 이벤트 및 제휴프로그램, 프로모션 제공',
    taskList: [
      '신규 기능에 필요한 공용 컴포넌트 개발',
      '중고폰, 중고폰 + 유심, 유심 주문 서비스 개발',
      '마이페이지 개발',
      '주문 배송 관리',
      '자사 망을 이용하는 고객 한에 사용 중인 요금제, 부가서비스 표시 및 Guage 차트를 이용한 잔여 데이터, 음성, 문자 시각화',
      'NICE, 카카오페이 본인인증과 KCP를 이용한 결제 연동 (네이버 인증 추가 예정)',
      '라이브 서비스 이슈 대응',
      '마케팅 활용 목적으로 구글 애널리틱스 픽셀 연동',
      'AWS S3에 이미지 리소스 교체',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
      '기획/디자인 리뷰 참여',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2021.03 ~ 2022.02',
    // reference: ,
  },
  {
    workId: '21',
    imageName: 'img-one-click',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'One Click (자사 서비스)',
    target: '',
    skill: 'Vue.js, javascript, Stylus, ES6',
    introduction:
      '고객과 상담원의 통화를 진행으로, 고객이 상담원의 안내에 따라 조금 더 쉽고 빠르게 상품 주문을 제공하는 모바일웹 서비스',
    taskList: [
      '프로젝트 셋업 및 공용 컴포넌트 개발',
      '신규가입, 번호이동, 기기변경에 대한 주문 서비스 개발',
      'NICE 본인 인증 (휴대폰/신용카드) 연동',
      'KCP 결제 모듈 연동',
      '기획/디자인 리뷰 참여',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2021.02 ~ 2021.02',
  },
  {
    workId: '20',
    imageName: 'img-smartphoneshop-home',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: '스마트폰샵 (자사 서비스)',
    target: '',
    skill: 'React.js, javascript, ES6, Styled-compoments',
    introduction:
      '카카오페이에서 제공해주며 고객이 대리점 방문하지 않고 휴대폰(5G) 주문부터 개통까지 지원하는 서비스',
    taskList: [
      '프론트엔드 개발 및 유지보수',
      '라이브 서비스 이슈 대응',
      '핀다이렉트샵(자사 서비스) 업데이트시 동기화 작업',
      'AWS S3에 이미지 리소스 교체',
      '기획/디자인 리뷰 참여',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2021.01 ~ 2022.02',
    // reference: ,
  },
  {
    workId: '19',
    imageName: 'img-pindirectshop',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: '프로모션 홈페이지',
    target: '',
    skill: 'GatsBy, javascript, HTML5, CSS3',
    introduction:
      '신규 스마트폰 출시에 따른 사전 예약 및 다양한 프로모션 그리고 이벤트 혜택등을 고객들에게 공지하고 안내하는 홈페이지',
    taskList: [
      '신규 출시되는 스마트폰과 다양한 프로모션과 이벤트에 맞게 내용 수정',
      'AWS S3에 이미지 리소스 교체',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2021.01 ~ 2021.01',
    // reference: ,
  },
  {
    workId: '18',
    imageName: 'img-loadcell-map-view',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'BuildThing Loadcell Server (자사 서비스)',
    target: '',
    skill:
      'Quasar Framework, Vue.js, jQuery, JavaScript, Stylus, Flask babel, GridStack.js, Open Api, Kendo UI',
    introduction:
      '신규 개발 제품 Loadcell(하중 압력 측정)의 데이터를 Gateway로 부터 수신 받아 SDK를 통하여 스트레인게이지 변화 값을 통해 하중 값으로 변환하여 현재 하중이 얼마나 되는지 차트 및 mapVIew로 모니터링 서비스 제공해주며 하중 상태에 따라 WebSocket을 통한 푸시 알림 제공',
    taskList: [
      '프론트엔드 개발',
      'Quasar Framework와 Kendo UI에서 제공해주는 컴포넌트를 통해 공용 컴포넌트 개발',
      '맵뷰에 표시되는 Loadcell 아이콘 클릭시 현재 하중에 대한 데이터를 plotly.js를 사용하여 3D 차트 표시',
      '각 종 UI 컴포넌트를 통해 담당 페이지 기능 구현 및 시각화',
      'PG사 연동을 통한 결제 기능 구현 및 그룹 관리 기능 구현',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2020.11 ~ 2020.11',
  },
  {
    workId: '17',
    imageName: 'img-security',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Mobile'],
    workName: 'BuildThing Loadcell Admin (자사 서비스)',
    target: '',
    skill:
      'Quasar Framework, Vue.js, jQuery, JavaScript, Stylus, Flask babel, GridStack.js, Open Api, Kendo UI',
    introduction:
      '신규 개발 제품 Loadcell(하중 압력 측정), Gateway를 자사에서 개발한 SDK를 사용하여 Bluetooth로 연결을 통해 탄성체 내에 스트레인게이지를 부착하여 탄성체에 압력이 가해져 스트레인게이지 변화 값을 통해 하중 값으로 변환하여 현재 하중이 얼마나 되는지 모니터링 서비스 제공해주며 하중 상태에 따라 WebSocket을 통한 푸시 알림 제공',
    taskList: [
      '프론트엔드 개발',
      'Quasar Framework에서 제공해주는 Cordova를 통해 하이브리드 앱 개발 환경 셋업',
      'Quasar Framework와 Kendo UI에서 제공해주는 컴포넌트를 통해 공용 컴포넌트 개발',
      'Android 부분을 담당하여 개발',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2020.11 ~ 2020.11',
    // reference: ,
  },
  {
    workId: '16',
    imageName: 'img-security',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Mobile'],
    workName: 'BuildThing Loadcell (자사 서비스)',
    target: '',
    skill: 'Quasar Framework, Cordova, Vue.js, javascript, Stylus, ES6',
    introduction:
      '신규 개발 제품 Loadcell(하중 압력 측정)을 통해 탄성체 내에 스트레인게이지를 부착하여 탄성체에 압력이 가해져 스트레인게이지 변화 값을 통해 하중 값으로 변환하여 현재 하중이 얼마나 되는지 모니터링 서비스 제공',
    taskList: [
      '프론트엔드 개발',
      'Quasar Framework에서 제공해주는 Cordova를 통해 하이브리드 앱 개발 환경 셋업',
      'Quasar Framework와 제공해주는 컴포넌트를 통해 공용 컴포넌트 개발',
      'Android 부분을 담당하여 개발',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2020.10 ~ 2020.11',
    // reference: ,
  },
  {
    workId: '15',
    imageName: 'img-iaq-cloud-dashboard',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'BuildThing IAQ Cloud (자사 서비스)',
    target: '',
    skill:
      'Quasar Framework, Vue.js, jQuery, JavaScript, Stylus, Flask babel, GridStack.js, leaflet.js, Open Api, Kendo UI',
    introduction:
      '신규 개발 제품 IAQ (실내 공기질 측정), Gateway를 통해 공간 및 기기 관리를 통해 IAQ, Gateway 등록 관리 및 실내 공기질 수치 정보 제공',
    taskList: [
      '프론트엔드 개발',
      'Quasar Framework와 Kendo UI에서 제공해주는 컴포넌트를 통해 공용 컴포넌트 개발',
      'Gridstack.js를 사용하여 대시보드 카드 생성, 편집(위치 이동), 삭제 기능 구현',
      '자사에서 개발한 SDK와 각 종 UI 컴포넌트를 통해 담당 페이지 기능 구현 및 시각화',
      'PG사 연동을 통한 결제 기능 구현 및 그룹 관리 기능 구현',
      'Flask babel을 이용하여 SSR 렌더링을 통한 이용 약관에 관련된 페이지의 다국어 message.pot로 적용',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2020.08 ~ 2020.09',
    reference: 'https://www.youtube.com/watch?v=YdbAktMYipU',
  },
  {
    workId: '14',
    imageName: 'img-iaq-admin',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Mobile'],
    workName: 'BuildThing IAQ Admin (자사 서비스)',
    target: '',
    skill: 'Quasar Framework, Cordova, Vue.js, JavaScript, Stylus, Open Api, Kendo UI',
    introduction:
      '신규 개발 제품 IAQ(실내 공기질 측정), Gateway를 자사에서 개발한 SDK를 사용하여 Bluetooth로 연결, 공간 및 기기 관리를 통해 IAQ, Gateway 등록 관리 및 실내 공기질 수치 정보 제공해주며 공기질 상태에 따라 WebSocket을 통한 푸시 알림 제공',
    taskList: [
      '프론트엔드 개발',
      'Quasar Framework에서 제공해주는 Cordova를 통해 하이브리드 앱 개발 환경 셋업',
      'Quasar Framework와 Kendo UI에서 제공해주는 컴포넌트를 통해 공용 컴포넌트 개발',
      'Android 부분을 담당하여 개발 및 구글 플레이 스토어 배포',
      '자사에서 개발한 SDK와 캐러셀 등 공용 컴포넌트를 통해 담당 페이지 구현 및 시각화',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2020.08 ~ 2020.08',
    reference: 'https://www.youtube.com/watch?v=YdbAktMYipU',
  },
  {
    workId: '13',
    imageName: 'img-buildthing-admin',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Mobile', 'Desktop'],
    workName: 'BuildThing Admin v1.1 (자사 서비스)',
    target: '',
    skill: 'Quasar Framework, Cordova, Electron, Vue.js, JavaScript, Stylus, Kendo UI',
    introduction:
      '자사 개발 제품 BuildThing Beacon(실내 공기질 측정)과 BuildThing Gateway를 자사에서 개발한 SDK를 사용하여 Bluetooth로 연결을 통해 영역 마다 설치되어있는 비콘과 게이트웨이부터 받아온 데이터를 기반으로 실시간 모니터링 및 웹 소켓을 통한 푸시 알람으로 영역을 관리하며 데이터를 시각화 해주는 앱',
    taskList: [
      '프론트엔드 개발',
      '신규 개발 제품 Gateway에 대한 관련 기능 및 UI 변경 사항 반영',
      'Android와 Window 앱 담당 및 구글 플레이 스토어, 마이크로스토어 배포',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2020.08 ~ 2020.08',
    reference: 'https://play.google.com/store/apps/details?id=kr.buildit.buildthing.ble',
  },
  {
    workId: '12',
    imageName: 'img-iaq-scan',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Mobile'],
    workName: 'BuildThing IAQ (자사 서비스)',
    target: '',
    skill: 'Quasar Framework, Cordova, Vue.js, JavaScript, Stylus, Open Api, Kendo UI',
    introduction:
      '신규 개발 제품 IAQ(실내 공기질 측정)를 통해 주변 IAQ 기기를 자사에서 개발한 SDK를 사용하여 Bluetooth로 연결을 통해 현재 위치 한 건물 내의 실내 공기질 수치 정보 제공 및 실내 공기질 요소별 등급과 환기 조치 가이드 제공',
    taskList: [
      '프론트엔드 개발',
      'Quasar Framework에서 제공해주는 Cordova를 통해 하이브리드 앱 개발 환경 셋업',
      'Quasar Framework와 Kendo UI에서 제공해주는 컴포넌트를 통해 공용 컴포넌트 개발',
      'Android 부분을 담당하여 개발 및 구글 플레이 스토어 배포',
      '자사에서 개발한 SDK와 각 종 UI 컴포넌트를 통해 담당 페이지 기능 구현 및 시각화',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2020.08 ~ 2020.08',
    reference:
      'https://play.google.com/store/apps/details?id=kr.buildit.buildthing.airquality.scan',
  },
  {
    workId: '11',
    imageName: 'img-cloud-beacon',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'BuildThing Cloud v1.1 (자사 서비스)',
    target: '',
    skill: 'Quasar Framework, Vue.js, JavaScript, Stylus, Kendo UI',
    introduction:
      '자사 개발 제품 BuildThing Beacon(실내 공기질 측정)과 BuildThing Gateway를 자사에서 개발한 SDK를 사용하여 Bluetooth로 연결을 통해 영역 마다 설치되어있는 비콘과 게이트웨이로부터 받아온 데이터를 기반으로 실시간 모니터링 및 웹 소켓을 통한 푸시 알람으로 영역을 관리하며 데이터를 시각화 해주는 웹 서비스',
    taskList: [
      '프론트엔드 개발',
      '신규 개발 제품 Gateway에 대한 관련 기능 및 UI 변경 사항 반영',
      'Flask babel을 이용하여 SSR 렌더링을 통한 이용 약관에 관련된 페이지의 다국어 message.pot로 적용',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2019.07 ~ 2019.08',
  },
  {
    workId: '10',
    imageName: 'img-smart-building',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'B.IOT v1.3(Lite) (스마트 빌딩 솔루션)',
    target: '',
    skill:
      'Spring boot Framework, MVVM pattern, jQuery, JavaScript, GridStack.js, i18n.js, HTML5, CSS3, Kendo UI',
    introduction:
      '건물 관리 자동화와 건물 에너지 절감을 위한 솔루션의 개발을 위해 진행 되었고 Web 화면을 통해 특정 건물에 설치된 각 종 기기들을 관리하고 실시간으로 모니터링 및 원격 제어하며, 해당 기기들의 이력과 통계 데이터를 확인할 수 있습니다. 또한 실시간 알람을 통해 건물 내 주요 이슈 현황을 파악',
    taskList: [
      '프론트엔드 유지보수 및 개발',
      '담당 페이지에 대한 각 종 컴포넌트를 통한 신규 및 추가 기능 개발',
      '담당 페이지에 대한 개선 사항 반영 및 현장 이슈 대응',
      '유지보수 및 Chrom inspector를 통한 성능 개선',
      '고객사의 디자인 가이드 라인을 제공 받아 디자인 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2020.03 ~ 2020.10',
    reference:
      'https://www.google.com/search?sca_esv=dfa970682d15eccc&rlz=1C5CHFA_enKR1013KR1013&sxsrf=ADLYWIKhi8FJOBW2VlENcj1AjSXw1Udh9A:1734137137358&q=%EC%82%BC%EC%84%B1+biot&udm=2&fbs=AEQNm0DmKhoYsBCHazhZSCWuALW8l8eUs1i3TeMYPF4tXSfZ98Z_XVxzNb13fp2atSe3aTZd-aSEBmENVJrVMvMoQtba8z4LlvriC013vj4TZAy0wOm-Zagsy73SgWUQp-yiJWyM2BsF6inJTE4jd3taYYknQeszS3_K58WeeRsEKU2k-UMzYwD-07yUpqcIXXjX8sDDr1VRQq2fH20eA8Dz1rYYBU3lIg&sa=X&sqi=2&ved=2ahUKEwifpcGghKaKAxVkzjQHHWC2KVEQtKgLegQIFhAB&biw=1920&bih=963&dpr=1#imgrc=z54xUXrdTjfLJM&imgdii=VKF9crJwXhfEtM',
  },
  {
    workId: '9',
    imageName: 'img-buildit-homepage',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: '자사 홈페이지',
    target: '',
    skill: 'Quasar Framework, Vue.js, TypeScript, JavaScript, i18n.js, Stylus',
    introduction: '2020년도 자사 홈페이지 리뉴얼',
    taskList: [
      '프론트엔드 개발',
      'Vue.js만 사용하던 이전과 다르게 TypeScript를 함께 사용 및 환경 셋업',
      'Quasar Framework에서 지원해주는 컴포넌트 및 그리드 레이아웃을 통해 반응형 개선',
      '이전 홈페이지에서 신규 페이지 및 변경 된 페이지 개발',
      '공용 컴포넌트 개발',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2020.02 ~ 2020.03',
    reference: 'https://buildit.kr/',
  },
  {
    workId: '8',
    imageName: 'img-smart-building',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'B.IOT v1.2(Enterprise) (스마트 빌딩 솔루션)',
    target: '',
    skill:
      'Spring boot Framework, MVVM pattern, jQuery, JavaScript, GridStack.js, i18n.js, HTML5, CSS3, Kendo UI',
    introduction:
      '건물 관리 자동화와 건물 에너지 절감을 위한 솔루션의 개발을 위해 진행 되었고 Web 화면을 통해 특정 건물에 설치된 각 종 기기들을 관리하고 실시간으로 모니터링 및 원격 제어하며, 해당 기기들의 이력과 통계 데이터를 확인할 수 있습니다. 또한 실시간 알람을 통해 건물 내 주요 이슈 현황을 파악',
    taskList: [
      '프론트엔드 유지보수 및 개발',
      '인수인계 받은 담당 페이지에 대한 개선 사항 개발',
      '담당 페이지 유지보수 및 Chrom inspector를 통한 성능 개선',
      '고객사의 디자인 가이드 라인을 제공 받아 디자인 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2019.05 ~ 2020.02',
    reference:
      'https://www.google.com/search?sca_esv=dfa970682d15eccc&rlz=1C5CHFA_enKR1013KR1013&sxsrf=ADLYWIKhi8FJOBW2VlENcj1AjSXw1Udh9A:1734137137358&q=%EC%82%BC%EC%84%B1+biot&udm=2&fbs=AEQNm0DmKhoYsBCHazhZSCWuALW8l8eUs1i3TeMYPF4tXSfZ98Z_XVxzNb13fp2atSe3aTZd-aSEBmENVJrVMvMoQtba8z4LlvriC013vj4TZAy0wOm-Zagsy73SgWUQp-yiJWyM2BsF6inJTE4jd3taYYknQeszS3_K58WeeRsEKU2k-UMzYwD-07yUpqcIXXjX8sDDr1VRQq2fH20eA8Dz1rYYBU3lIg&sa=X&sqi=2&ved=2ahUKEwifpcGghKaKAxVkzjQHHWC2KVEQtKgLegQIFhAB&biw=1920&bih=963&dpr=1#imgrc=z54xUXrdTjfLJM&imgdii=VKF9crJwXhfEtM',
  },
  {
    workId: '7',
    imageName: 'img-security',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'A4S (보안 정보 모니터링 솔루션)',
    target: '',
    skill: 'Spring boot Framework, Vue.js, jQuery, JavaScript, GridStack.js, Stylus, Kendo UI',
    introduction:
      '삼성리서치 연구 과제로 사용자 권한 별, 툴 별, 과제 별, 조직 별의 보안 관련 정보의 조회가 가능하며 각 종 차트를 통한 보안 관련 정보 시각화 및 사용자가 직접 추가/편집이 가능한 사용자 정의형 대시보드와 사용자 및 권한 관리가 주요 기능인 웹 서비스',
    taskList: [
      '프론트엔드 개발',
      'Kendo UI에서 제공해주는 차트 컴포넌트를 통해 데이터 시각화',
      '요구사항에 맞게 각 종 컴포넌트를 사용하여 각 페이지의 기능 구현',
      'Gridstack.js를 사용하여 대시보드 카드 및 추가, 편집, 삭제 구현',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2019.05 ~ 2019.10',
  },
  {
    workId: '6',
    imageName: 'img-buildthing-cloud',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'BuildThing Cloud v1.0 (자사 서비스)',
    target: '',
    skill: 'Quasar Framework, Vue.js, JavaScript, Stylus, Kendo UI',
    introduction:
      '자사 개발 제품 BuildThing Beacon(실내 공기질 측정)으로 자사에서 개발한 SDK를 사용하여 Bluetooth로 연결을 통해 영역 마다 설치되어있는 비콘으로부터 받아온 데이터를 기반으로 실시간 모니터링 및 웹 소켓을 통한 푸시 알람으로 영역을 관리하며 데이터를 시각화 해주는 서비스',
    taskList: [
      '프론트엔드 개발',
      'Chart.js를 Kendo UI의 차트로 변경 수행 및 추가 된 센서 데이터 시각화 구현',
      '리뉴얼 한 대시보드 페이지 외에 담당 페이지를 Kendo UI에서 제공하는 컴포넌트 및 기존에 구현 되어있는 공용 컴포넌트를 통해 요구사항에 맞게 기능 구현',
      '디자이너와의 협업으로 제플린을 통해 디자인 가이드라인 내용 반영',
    ],
    versionManage: 'Git(SourceTree)',
    period: '2019.05 ~ 2019.05',
  },
  {
    workId: '5',
    imageName: 'img-factory',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: '제철소 MES 시스템 2.0',
    target: '',
    skill: 'Spring Framework, MVC pattern, JavaScript, HTML, CSS3, Oracle',
    introduction:
      'MES 시스템 유지보수 및 운영을 통해 현장 이슈 대응과 업무 Flow 개선으로 생산성 향상과 편의 제공',
    taskList: [
      '시스템 운영 및 유지보수',
      'MES시스템(포항 / 광양)의 구내운송 부분의 운송장비 관리 및 모니터링 그리고 계량 부분을 담당',
      '업무 Flow에 대한 개선 안에 대해 개발 진행',
      '제철소 특성으로 연중 무휴로 가동되기 때문에 야간/주말에 발생하는 현장의 전산 이슈에 대해 다른 팀원들과 함께 협업을 통하여 대응',
      '코드 수정 및 신규 기능으로 인해 추가 된 코드를 종합하여 운영 서버에서 테스트 이후 정기 이행일에 맞추어 가동계 서버로 자원 이행',
    ],
    versionManage: 'Serena Demension',
    period: '2018.04 ~ 2018.12',
  },
  {
    workId: '4',
    imageName: 'img-swc-web',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'SWC 웹 (자사 서비스)',
    target: '',
    skill: 'Spring Framework, MVC pattern, Java, Mybatis, Oracle, jQuery, JavaScript, HTML5, CSS3',
    introduction:
      '입주민 및 외부인이 웹페이지를 통하여 단지 내의 시설 이용 활성화 및 편의 제공해주는 아파트 커뮤니티 서비스',
    taskList: [
      '프론트엔드 개발',
      '아파트 커뮤니티 웹 사이트와 키오스크 개발을 진행하였으며 주 업무로 웹 사이트의 시스템 관리 부분의 화면과 키오스크의 도서관 좌석 배정, 골프장 타석 배정, 게스트룸 객실 관리 부분의 페이지를 담당',
      '쿼리문 작성과 공용 컴포넌트를 통해 각 페이지의 요구사항에 맞게 데이터를 가공하여 기능 구현',
      '퍼블리셔와의 협업으로 제공해준 기본 Layout 내에서 디자인 가이드라인 반영',
    ],
    versionManage: 'SVN',
    period: '2017.11 ~ 2018.03',
  },
  {
    workId: '3',
    imageName: 'img-swc-web',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'SWC 키오스크 (자사 서비스)',
    target: '',
    skill: 'Spring Framework, MVC pattern, Java, Mybatis, Oracle, jQuery, JavaScript, HTML5, CSS3',
    introduction:
      '입주민 및 외부인이 키오스크를 통하여 단지 내의 시설 이용 활성화 및 편의 제공해주는 아파트 커뮤니티 서비스',
    taskList: [
      '프론트엔드 개발',
      '아파트 커뮤니티 웹 사이트와 키오스크 개발을 진행하였으며 주 업무로 웹 사이트의 시스템 관리 부분의 화면과 키오스크의 도서관 좌석 배정, 골프장 타석 배정, 게스트룸 객실 관리 부분의 페이지를 담당',
      '쿼리문 작성과 공용 컴포넌트를 통해 각 페이지의 요구사항에 맞게 데이터를 가공하여 기능 구현',
      '퍼블리셔와의 협업으로 제공해준 기본 Layout 내에서 디자인 가이드라인 반영',
    ],
    versionManage: 'SVN',
    period: '2018.02 ~ 2018.03',
  },
  {
    workId: '2',
    imageName: 'img-erp',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: '통합 IT 시스템 구축',
    target: '',
    skill: 'X-PLATFORM, JavaScript, Oracle',
    introduction: 'ERP 시스템 구축으로 보다 효율적인 업무 진행과 생산성 향상',
    taskList: [
      '프론트엔드 개발',
      '투비소프트의 X-PLATFORM 을 사용하여 ERP시스템의 구매 부분을 담당',
      'X-PLATFORM에서 제공해주는 컴포넌트를 통해 가이드 라인 반영',
      '필요한 데이터에 맞게 쿼리문 작성과 플랫폼에서 제공해주는 컴포넌트를 통해 요구사항에 맞게 기능 구현',
    ],
    versionManage: 'SVN',
    period: '2017.06 ~ 2017.10',
  },
  {
    workId: '1',
    imageName: 'img-swc-web',
    // type: THUMBNAIL_TYPES.PROJECT,
    tagNames: ['Web'],
    workName: 'SWC 월패드 (자사 서비스)',
    target: '',
    skill: 'Spring Framework, MVC pattern, Java, Mybatis, Oracle, jQuery, JavaScript, HTML5, CSS3',
    introduction:
      '입주민이 실내에서 Wall-Pad를 통하여 단지 내의 시설 예약 및 관리비 정산 등의 편의를 제공해주는 아파트 커뮤니티 서비스',
    taskList: [
      '프론트엔드 개발',
      '아파트 커뮤니티 웹 사이트와 키오스크 개발을 진행하였으며 주 업무로 웹 사이트의 시스템 관리 부분의 화면과 키오스크의 도서관 좌석 배정, 골프장 타석 배정, 게스트룸 객실 관리 부분의 페이지를 담당',
      '쿼리문 작성과 공용 컴포넌트를 통해 각 페이지의 요구사항에 맞게 데이터를 가공하여 기능 구현',
      '퍼블리셔와의 협업으로 제공해준 기본 Layout 내에서 디자인 가이드라인 반영',
    ],
    versionManage: 'SVN',
    period: '2017.04 ~ 2017.05',
  },
];

// common button의 type
export const COMMON_BUTTON_TYPES: { [key: string]: CommonButtonType } = {
  BLACK: 'BLACK',
  WHITE: 'WHITE',
};

// Common GridCard Size Types
export const COMMON_CARD_SIZE_TYPES: CommonGridCardSizeProps = {
  SMALL: 'SMALL',
  MEDIUM: 'MEDIUM',
  LARGE: 'LARGE',
  FULL: 'FULL',
};

// Common Position Type
export const COMMON_POSITION_TYPES: CommonPositionProps = {
  LEFT_TOP: 'LEFT_TOP',
  LEFT_BOTTOM: 'LEFT_BOTTOM',
  RIGHT_TOP: 'RIGHT_TOP',
  RIGHT_BOTTOM: 'RIGHT_BOTTOM',
};

// LEVEL Type
export const COMMON_LEVEL_TYPES: CommonLevelTypeProps = {
  MAIN: 'MAIN',
  SUB: 'SUB',
};

// External Link
export const EXTERNAL_LINK_LIST: ExternalTypeProps[] = [
  { name: 'NC ITS', type: 'link', url: 'https://www.ncsoft.com' },
  { name: 'StageFive', type: 'link', url: 'https://www.stagefive.com' },
  { name: 'Buildit', type: 'link', url: 'https://buildit.kr' },
  { name: 'Atos', type: 'link', url: 'https://www.atos.co.kr' },
  { name: 'File', type: 'file', url: '' },
];
